### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by rnakaa** [Yono1112/ft_cub3d#16]
**Describe the bug**
- [x] ceiling とfloorをint配列に持たせる
- [x] 壁に穴があるとvalidされる
- [x] 床と壁の数値バグ（最初の値が受け取れてない）
- [x] セグフォ
- [x] -wall -wextra -werror
- [x] free関数
- [x] mapが二つあった時の対処
- [ ] holecheck作り直し（is_edge(i,j,mapdata)を作る）

**Comment by Yono1112** [comment]
freeする関数も

**Comment by rnakaa** [comment]
セグフォ
最下層の次がeofだとセグフォする

**Comment by Yono1112** [comment]
- [x] gccをccにする

**Comment by rnakaa** [comment]
check_holeのif文の順よがよくない
新しく辺を感知する関数を作る
